### ISSUE TITLE
Uncaught exception on socket connection

### ISSUE THREAD

**Issue by Taraman17** [FreshlyBrewedCode/pymee#37]
When trying to connect, an "OSError" can occur, which is not cought:
```
2024-09-29 04:24:41.680 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pymee/__init__.py", line 151, in run
    await self.open_ws()
  File "/usr/local/lib/python3.12/site-packages/pymee/__init__.py", line 173, in open_ws
    async with websockets.connect(
  File "/usr/local/lib/python3.12/site-packages/websockets/legacy/client.py", line 635, in __aenter__
    traceback: Optional[TracebackType],
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/websockets/legacy/client.py", line 654, in __await_impl__
    await protocol.handshake(
                           ^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1122, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1104, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1007, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 641, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 681, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.170.131', 7681)
```

**Comment by Taraman17** [comment]
Fixed with Release 2.3.0
